apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sast-ai
  namespace: sast-ai
  labels:
    app.kubernetes.io/name: sast-ai
    app.kubernetes.io/part-of: sast-ai
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RHEcosystemAppEng/sast-ai-orchestrator.git
    targetRevision: HEAD
    path: deploy/sast-ai-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sast-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10 