{{- if .Values.minio.enabled }}
# MinIO Root Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sast-ai.fullname" . }}-minio-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sast-ai.labels" . | nindent 4 }}
    component: minio-storage
    secret-type: credentials
  {{- with (include "sast-ai.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.minio.credentials.rootUser }}
  MINIO_ROOT_USER: {{ .Values.minio.credentials.rootUser | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.credentials.rootPassword | b64enc }}
  {{- else }}
  MINIO_ROOT_USER: {{ "admin" | b64enc }}
  MINIO_ROOT_PASSWORD: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
---
# MinIO Console Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sast-ai.fullname" . }}-minio-console-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sast-ai.labels" . | nindent 4 }}
    component: minio-storage
    secret-type: console-credentials
  {{- with (include "sast-ai.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.minio.credentials.consoleUser }}
  CONSOLE_ACCESS_KEY: {{ .Values.minio.credentials.consoleUser | b64enc }}
  CONSOLE_SECRET_KEY: {{ .Values.minio.credentials.consolePassword | b64enc }}
  {{- else }}
  CONSOLE_ACCESS_KEY: {{ "console-admin" | b64enc }}
  CONSOLE_SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
---
# MinIO Client Access Credentials for SAST-AI Services
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sast-ai.fullname" . }}-minio-client-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sast-ai.labels" . | nindent 4 }}
    component: minio-storage
    secret-type: client-credentials
  {{- with (include "sast-ai.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
    # Used by SAST-AI Orchestrator and Workflow for S3 client access
  {{- end }}
type: Opaque
data:
  # S3 compatible client credentials
  S3_ACCESS_KEY: {{ "sast-ai-client" | b64enc }}
  S3_SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
  S3_ENDPOINT: {{ printf "%s-minio-hl.%s.svc.cluster.local:9000" (include "sast-ai.fullname" .) .Release.Namespace | b64enc }}
  S3_REGION: {{ "us-east-1" | b64enc }}
  S3_BUCKET_DATASETS: {{ .Values.minio.buckets.datasets | b64enc }}
  S3_BUCKET_TEMP: {{ .Values.minio.buckets.temp | b64enc }}
  S3_USE_SSL: {{ "false" | b64enc }}
{{- end }}