{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sast-ai.fullname" . }}-postgresql
  labels:
    {{- include "sast-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- with (include "sast-ai.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sast-ai.fullname" . }}-postgresql-anyuid
  labels:
    {{- include "sast-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- with (include "sast-ai.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: {{ include "sast-ai.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
{{- end }} 