{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sast-ai.serviceAccountName" . }}
  labels:
    {{- include "sast-ai.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "sast-ai.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }} 