apiVersion: v1
kind: Service
metadata:
  name: {{ include "sast-ai.fullname" . }}
  labels:
    {{- include "sast-ai.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "sast-ai.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sast-ai.selectorLabels" . | nindent 4 }} 